// <auto-generated />
using App.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505144728_AddUrlManual")]
    partial class AddUrlManual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("App.Domain.Entities.SiteDeployConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("destino");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("ProjetoIis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("projeto_iis");

                    b.Property<string>("UrlManual")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("url_manual");

                    b.HasKey("Id");

                    b.ToTable("site_deploy_config", (string)null);
                });

            modelBuilder.Entity("App.Domain.Entities.SiteOrigemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int>("SiteDeployConfigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("site_deploy_config_id");

                    b.Property<string>("Variavel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("variavel");

                    b.HasKey("Id");

                    b.HasIndex("SiteDeployConfigId");

                    b.ToTable("site_origem_config", (string)null);
                });

            modelBuilder.Entity("App.Domain.Entities.SiteOrigemConfig", b =>
                {
                    b.HasOne("App.Domain.Entities.SiteDeployConfig", "SiteDeployConfig")
                        .WithMany("Origens")
                        .HasForeignKey("SiteDeployConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteDeployConfig");
                });

            modelBuilder.Entity("App.Domain.Entities.SiteDeployConfig", b =>
                {
                    b.Navigation("Origens");
                });
#pragma warning restore 612, 618
        }
    }
}
