// <auto-generated />
using App.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("App.Domain.Entities.SiteDeployConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Atualizada")
                        .HasColumnType("INTEGER")
                        .HasColumnName("atualizada");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("destino");

                    b.Property<string>("ProjetoIis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("projeto_iis");

                    b.Property<string>("Svn")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("svn");

                    b.Property<string>("UrlManual")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("url_manual");

                    b.HasKey("Id");

                    b.ToTable("site_deploy_config", (string)null);
                });

            modelBuilder.Entity("App.Domain.Entities.SiteOrigemConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Conteudo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("conteudo");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("SiteDeployConfigId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("site_deploy_config_id");

                    b.HasKey("Id");

                    b.HasIndex("SiteDeployConfigId");

                    b.ToTable("site_origem_config", (string)null);
                });

            modelBuilder.Entity("App.Domain.Entities.SiteOrigemConfig", b =>
                {
                    b.HasOne("App.Domain.Entities.SiteDeployConfig", "SiteDeployConfig")
                        .WithMany("Origens")
                        .HasForeignKey("SiteDeployConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteDeployConfig");
                });

            modelBuilder.Entity("App.Domain.Entities.SiteDeployConfig", b =>
                {
                    b.Navigation("Origens");
                });
#pragma warning restore 612, 618
        }
    }
}
